In [9]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

In [71]:
driver = webdriver.Chrome('C:\\Users\\Qianhua\\AppData\\Local\\Temp\\Temp1_chromedriver_win32.zip\\chromedriver.exe')

In [72]:
driver.get('https://publicholidays.com/us/school-holidays/')

In [73]:
states = []
regions = []
dates = []
content = driver.page_source
soup = BeautifulSoup(content)
#print(soup.prettify)
for a in soup.findAll('a', href = True)[23:74]:
    state = a.text
    driver.get(a.get('href'))
    content2 = driver.page_source
    soup2 = BeautifulSoup(content2)
    for b in soup2.findAll('a', href = True)[23:-48]:
        region = b.text
        try:
            driver.get(b.get('href'))
            content3 = driver.page_source
        except:
            print('An error occurs :(')
        soup3 = BeautifulSoup(content3)
        if len(soup3.findAll('td')) > 0:
            date = soup3.findAll('td')[1]
            states.append(state)
            regions.append(region)
            dates.append(date)

In [121]:
import datetime
import numpy as np

date = []
for i in dates:
    try: 
        d = str(i).split('<td>')[1].split('<br/>')[0]
        date.append(datetime.datetime.strptime(d, '%d %b %Y'))
    except:
        print(i)
        ind = dates.index(i)
        print(states[ind])
        date.append(datetime.datetime(2021, 8, 19, 0, 0))

<td class="gsib_a" id="gs_tti50"><input autocomplete="off" class="gsc-input" dir="ltr" id="gsc-i-id1" name="search" placeholder="What are you looking for today?" size="10" spellcheck="false" style='width: 100%; padding: 0px; border: none; margin: 0px; height: auto; background: url("https://www.google.com/cse/static/images/1x/en/branding.png") left center no-repeat rgb(255, 255, 255); outline: none;' title="search" type="text"/></td>
District of Columbia

In [129]:
df = pd.DataFrame({'state':states, 'region':regions, 'date': date})
df = df[(df.state != 'District of Columbia')& (df.date > datetime.datetime(2021, 6, 19, 0, 0))]

In [137]:
df.groupby('state').agg({'date': [np.min, np.max]})

                     date
                     amin       amax
state
Alabama        2021-08-02 2021-08-20
Alaska         2021-08-10 2021-09-14
Arizona        2021-07-19 2021-08-26
Arkansas       2021-07-26 2021-08-18
California     2021-07-06 2021-09-13
Colorado       2021-08-03 2021-09-07
Connecticut    2021-08-25 2021-09-09
Delaware       2021-08-24 2021-09-08
Florida        2021-08-09 2021-08-23
Georgia        2021-07-28 2021-09-07
Idaho          2021-08-11 2021-09-07
Illinois       2021-08-02 2021-09-09
Indiana        2021-07-26 2021-09-09
Iowa           2021-08-23 2021-09-07
Kansas         2021-08-09 2021-09-07
Kentucky       2021-08-02 2021-09-07
Louisiana      2021-08-02 2021-08-23
Maine          2021-08-18 2021-09-07
Maryland       2021-08-18 2021-09-08
Massachusetts  2021-08-23 2021-09-09
Michigan       2021-07-26 2021-11-24
Minnesota      2021-08-16 2021-09-13
Mississippi    2021-07-22 2021-08-11
Missouri       2021-08-23 2021-09-07
Montana        2021-08-18 2021-09-07
Nebraska       2021-08-03 2021-08-24
Nevada         2021-08-09 2021-08-30
New Hampshire  2021-08-23 2021-09-09
New Jersey     2021-08-24 2021-09-20
New Mexico     2021-08-02 2021-08-23
New York       2021-08-09 2021-09-13
North Carolina 2021-07-23 2021-08-30
North Dakota   2021-08-16 2021-08-30
Ohio           2021-08-11 2021-09-08
Oklahoma       2021-08-02 2021-09-01
Oregon         2021-08-16 2021-09-13
Pennsylvania   2021-08-16 2021-09-09
Rhode Island   2021-08-27 2021-09-09
South Carolina 2021-07-22 2021-08-23
South Dakota   2021-08-16 2021-09-01
Tennessee      2021-07-21 2021-08-16
Texas          2021-07-12 2021-08-30
Utah           2021-08-12 2021-08-30
Vermont        2021-08-24 2021-09-07
Virginia       2021-07-26 2021-09-20
Washington     2021-08-02 2021-09-09
West Virginia  2021-08-05 2021-09-07
Wisconsin      2021-08-16 2021-09-07
Wyoming        2021-08-16 2021-09-07

In [138]:
df[df.state == 'Alabama']

       state                     region       date
0    Alabama     Alabaster City Schools 2021-08-19
1    Alabama       Macon County Schools 2021-08-04
2    Alabama   Albertville City Schools 2021-08-04
3    Alabama       Madison City Schools 2021-08-04
4    Alabama     Alexander City Schools 2021-08-18
..       ...                        ...        ...
117  Alabama  Lauderdale County Schools 2021-08-09
118  Alabama    Lawrence County Schools 2021-08-10
119  Alabama         Lee County Schools 2021-08-09
120  Alabama         Leeds City Schools 2021-08-11
121  Alabama   Limestone County Schools 2021-08-06

[121 rows x 3 columns]